import Head from 'next/head';
import { Hero, Layout, About, Footer } from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nick Firme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <Hero />
          <About />
        </main>
        <Footer />
      </Layout>
    </div>
  );
}
